/* Automatically @generated by tree-sitter v0.25.10 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 92
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 47
#define ALIAS_COUNT 0
#define TOKEN_COUNT 25
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 8
#define MAX_ALIAS_SEQUENCE_LENGTH 11
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 6
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_identifier = 1,
  sym_comment = 2,
  anon_sym_ns = 3,
  anon_sym_EQ = 4,
  anon_sym_NAME = 5,
  anon_sym_COLON = 6,
  anon_sym_DESCRIPTION = 7,
  anon_sym_STATES = 8,
  anon_sym_START_STATE = 9,
  anon_sym_CURRENT_STATE = 10,
  anon_sym_END_STATE = 11,
  anon_sym_EVENTS = 12,
  anon_sym_TRANSITIONS = 13,
  anon_sym_REACTIONS = 14,
  anon_sym_COMMA = 15,
  anon_sym_LPAREN = 16,
  anon_sym_RPAREN = 17,
  anon_sym_AT = 18,
  anon_sym_FROM = 19,
  anon_sym_TO = 20,
  anon_sym_WHEN = 21,
  anon_sym_DO = 22,
  anon_sym_FIRES = 23,
  sym_string = 24,
  sym_source_file = 25,
  sym_namespace_decl = 26,
  sym_fsm_definition = 27,
  sym_description_clause = 28,
  sym_states_clause = 29,
  sym_start_state_clause = 30,
  sym_current_state_clause = 31,
  sym_end_state_clause = 32,
  sym_events_clause = 33,
  sym_transitions_clause = 34,
  sym_reactions_clause = 35,
  sym_identifier_list = 36,
  sym_qualified_name = 37,
  sym_reference = 38,
  sym_transition_def = 39,
  sym_reaction_def = 40,
  sym_fires_clause = 41,
  aux_sym_source_file_repeat1 = 42,
  aux_sym_transitions_clause_repeat1 = 43,
  aux_sym_reactions_clause_repeat1 = 44,
  aux_sym_identifier_list_repeat1 = 45,
  aux_sym_fires_clause_repeat1 = 46,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [sym_comment] = "comment",
  [anon_sym_ns] = "ns",
  [anon_sym_EQ] = "=",
  [anon_sym_NAME] = "NAME",
  [anon_sym_COLON] = ":",
  [anon_sym_DESCRIPTION] = "DESCRIPTION",
  [anon_sym_STATES] = "STATES",
  [anon_sym_START_STATE] = "START_STATE",
  [anon_sym_CURRENT_STATE] = "CURRENT_STATE",
  [anon_sym_END_STATE] = "END_STATE",
  [anon_sym_EVENTS] = "EVENTS",
  [anon_sym_TRANSITIONS] = "TRANSITIONS",
  [anon_sym_REACTIONS] = "REACTIONS",
  [anon_sym_COMMA] = ",",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_AT] = "@",
  [anon_sym_FROM] = "FROM",
  [anon_sym_TO] = "TO",
  [anon_sym_WHEN] = "WHEN",
  [anon_sym_DO] = "DO",
  [anon_sym_FIRES] = "FIRES",
  [sym_string] = "string",
  [sym_source_file] = "source_file",
  [sym_namespace_decl] = "namespace_decl",
  [sym_fsm_definition] = "fsm_definition",
  [sym_description_clause] = "description_clause",
  [sym_states_clause] = "states_clause",
  [sym_start_state_clause] = "start_state_clause",
  [sym_current_state_clause] = "current_state_clause",
  [sym_end_state_clause] = "end_state_clause",
  [sym_events_clause] = "events_clause",
  [sym_transitions_clause] = "transitions_clause",
  [sym_reactions_clause] = "reactions_clause",
  [sym_identifier_list] = "identifier_list",
  [sym_qualified_name] = "qualified_name",
  [sym_reference] = "reference",
  [sym_transition_def] = "transition_def",
  [sym_reaction_def] = "reaction_def",
  [sym_fires_clause] = "fires_clause",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_transitions_clause_repeat1] = "transitions_clause_repeat1",
  [aux_sym_reactions_clause_repeat1] = "reactions_clause_repeat1",
  [aux_sym_identifier_list_repeat1] = "identifier_list_repeat1",
  [aux_sym_fires_clause_repeat1] = "fires_clause_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [sym_comment] = sym_comment,
  [anon_sym_ns] = anon_sym_ns,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_NAME] = anon_sym_NAME,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_DESCRIPTION] = anon_sym_DESCRIPTION,
  [anon_sym_STATES] = anon_sym_STATES,
  [anon_sym_START_STATE] = anon_sym_START_STATE,
  [anon_sym_CURRENT_STATE] = anon_sym_CURRENT_STATE,
  [anon_sym_END_STATE] = anon_sym_END_STATE,
  [anon_sym_EVENTS] = anon_sym_EVENTS,
  [anon_sym_TRANSITIONS] = anon_sym_TRANSITIONS,
  [anon_sym_REACTIONS] = anon_sym_REACTIONS,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_AT] = anon_sym_AT,
  [anon_sym_FROM] = anon_sym_FROM,
  [anon_sym_TO] = anon_sym_TO,
  [anon_sym_WHEN] = anon_sym_WHEN,
  [anon_sym_DO] = anon_sym_DO,
  [anon_sym_FIRES] = anon_sym_FIRES,
  [sym_string] = sym_string,
  [sym_source_file] = sym_source_file,
  [sym_namespace_decl] = sym_namespace_decl,
  [sym_fsm_definition] = sym_fsm_definition,
  [sym_description_clause] = sym_description_clause,
  [sym_states_clause] = sym_states_clause,
  [sym_start_state_clause] = sym_start_state_clause,
  [sym_current_state_clause] = sym_current_state_clause,
  [sym_end_state_clause] = sym_end_state_clause,
  [sym_events_clause] = sym_events_clause,
  [sym_transitions_clause] = sym_transitions_clause,
  [sym_reactions_clause] = sym_reactions_clause,
  [sym_identifier_list] = sym_identifier_list,
  [sym_qualified_name] = sym_qualified_name,
  [sym_reference] = sym_reference,
  [sym_transition_def] = sym_transition_def,
  [sym_reaction_def] = sym_reaction_def,
  [sym_fires_clause] = sym_fires_clause,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_transitions_clause_repeat1] = aux_sym_transitions_clause_repeat1,
  [aux_sym_reactions_clause_repeat1] = aux_sym_reactions_clause_repeat1,
  [aux_sym_identifier_list_repeat1] = aux_sym_identifier_list_repeat1,
  [aux_sym_fires_clause_repeat1] = aux_sym_fires_clause_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_ns] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_NAME] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DESCRIPTION] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STATES] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_START_STATE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_CURRENT_STATE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_END_STATE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EVENTS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_TRANSITIONS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_REACTIONS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_FROM] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_TO] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_WHEN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DO] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_FIRES] = {
    .visible = true,
    .named = false,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_namespace_decl] = {
    .visible = true,
    .named = true,
  },
  [sym_fsm_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_description_clause] = {
    .visible = true,
    .named = true,
  },
  [sym_states_clause] = {
    .visible = true,
    .named = true,
  },
  [sym_start_state_clause] = {
    .visible = true,
    .named = true,
  },
  [sym_current_state_clause] = {
    .visible = true,
    .named = true,
  },
  [sym_end_state_clause] = {
    .visible = true,
    .named = true,
  },
  [sym_events_clause] = {
    .visible = true,
    .named = true,
  },
  [sym_transitions_clause] = {
    .visible = true,
    .named = true,
  },
  [sym_reactions_clause] = {
    .visible = true,
    .named = true,
  },
  [sym_identifier_list] = {
    .visible = true,
    .named = true,
  },
  [sym_qualified_name] = {
    .visible = true,
    .named = true,
  },
  [sym_reference] = {
    .visible = true,
    .named = true,
  },
  [sym_transition_def] = {
    .visible = true,
    .named = true,
  },
  [sym_reaction_def] = {
    .visible = true,
    .named = true,
  },
  [sym_fires_clause] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_transitions_clause_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_reactions_clause_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_identifier_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_fires_clause_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_do_transition = 1,
  field_from = 2,
  field_local = 3,
  field_name = 4,
  field_namespace = 5,
  field_to = 6,
  field_uri = 7,
  field_when = 8,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_do_transition] = "do_transition",
  [field_from] = "from",
  [field_local] = "local",
  [field_name] = "name",
  [field_namespace] = "namespace",
  [field_to] = "to",
  [field_uri] = "uri",
  [field_when] = "when",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 2},
  [2] = {.index = 2, .length = 2},
  [3] = {.index = 4, .length = 1},
  [4] = {.index = 5, .length = 3},
  [5] = {.index = 8, .length = 3},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_name, 1},
    {field_uri, 3},
  [2] =
    {field_local, 5},
    {field_namespace, 3},
  [4] =
    {field_name, 2},
  [5] =
    {field_from, 4},
    {field_name, 0},
    {field_to, 7},
  [8] =
    {field_do_transition, 7},
    {field_name, 0},
    {field_when, 4},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 91,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(3);
      ADVANCE_MAP(
        '"', 1,
        '(', 8,
        ')', 9,
        ',', 7,
        '/', 2,
        ':', 6,
        '=', 5,
        '@', 10,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(11);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(12);
      if (lookahead != 0) ADVANCE(1);
      END_STATE();
    case 2:
      if (lookahead == '/') ADVANCE(4);
      END_STATE();
    case 3:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 4:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(4);
      END_STATE();
    case 5:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_AT);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(11);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(sym_string);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      ADVANCE_MAP(
        'C', 1,
        'D', 2,
        'E', 3,
        'F', 4,
        'N', 5,
        'R', 6,
        'S', 7,
        'T', 8,
        'W', 9,
        'n', 10,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == 'U') ADVANCE(11);
      END_STATE();
    case 2:
      if (lookahead == 'E') ADVANCE(12);
      if (lookahead == 'O') ADVANCE(13);
      END_STATE();
    case 3:
      if (lookahead == 'N') ADVANCE(14);
      if (lookahead == 'V') ADVANCE(15);
      END_STATE();
    case 4:
      if (lookahead == 'I') ADVANCE(16);
      if (lookahead == 'R') ADVANCE(17);
      END_STATE();
    case 5:
      if (lookahead == 'A') ADVANCE(18);
      END_STATE();
    case 6:
      if (lookahead == 'E') ADVANCE(19);
      END_STATE();
    case 7:
      if (lookahead == 'T') ADVANCE(20);
      END_STATE();
    case 8:
      if (lookahead == 'O') ADVANCE(21);
      if (lookahead == 'R') ADVANCE(22);
      END_STATE();
    case 9:
      if (lookahead == 'H') ADVANCE(23);
      END_STATE();
    case 10:
      if (lookahead == 's') ADVANCE(24);
      END_STATE();
    case 11:
      if (lookahead == 'R') ADVANCE(25);
      END_STATE();
    case 12:
      if (lookahead == 'S') ADVANCE(26);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_DO);
      END_STATE();
    case 14:
      if (lookahead == 'D') ADVANCE(27);
      END_STATE();
    case 15:
      if (lookahead == 'E') ADVANCE(28);
      END_STATE();
    case 16:
      if (lookahead == 'R') ADVANCE(29);
      END_STATE();
    case 17:
      if (lookahead == 'O') ADVANCE(30);
      END_STATE();
    case 18:
      if (lookahead == 'M') ADVANCE(31);
      END_STATE();
    case 19:
      if (lookahead == 'A') ADVANCE(32);
      END_STATE();
    case 20:
      if (lookahead == 'A') ADVANCE(33);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_TO);
      END_STATE();
    case 22:
      if (lookahead == 'A') ADVANCE(34);
      END_STATE();
    case 23:
      if (lookahead == 'E') ADVANCE(35);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_ns);
      END_STATE();
    case 25:
      if (lookahead == 'R') ADVANCE(36);
      END_STATE();
    case 26:
      if (lookahead == 'C') ADVANCE(37);
      END_STATE();
    case 27:
      if (lookahead == '_') ADVANCE(38);
      END_STATE();
    case 28:
      if (lookahead == 'N') ADVANCE(39);
      END_STATE();
    case 29:
      if (lookahead == 'E') ADVANCE(40);
      END_STATE();
    case 30:
      if (lookahead == 'M') ADVANCE(41);
      END_STATE();
    case 31:
      if (lookahead == 'E') ADVANCE(42);
      END_STATE();
    case 32:
      if (lookahead == 'C') ADVANCE(43);
      END_STATE();
    case 33:
      if (lookahead == 'R') ADVANCE(44);
      if (lookahead == 'T') ADVANCE(45);
      END_STATE();
    case 34:
      if (lookahead == 'N') ADVANCE(46);
      END_STATE();
    case 35:
      if (lookahead == 'N') ADVANCE(47);
      END_STATE();
    case 36:
      if (lookahead == 'E') ADVANCE(48);
      END_STATE();
    case 37:
      if (lookahead == 'R') ADVANCE(49);
      END_STATE();
    case 38:
      if (lookahead == 'S') ADVANCE(50);
      END_STATE();
    case 39:
      if (lookahead == 'T') ADVANCE(51);
      END_STATE();
    case 40:
      if (lookahead == 'S') ADVANCE(52);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_FROM);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_NAME);
      END_STATE();
    case 43:
      if (lookahead == 'T') ADVANCE(53);
      END_STATE();
    case 44:
      if (lookahead == 'T') ADVANCE(54);
      END_STATE();
    case 45:
      if (lookahead == 'E') ADVANCE(55);
      END_STATE();
    case 46:
      if (lookahead == 'S') ADVANCE(56);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_WHEN);
      END_STATE();
    case 48:
      if (lookahead == 'N') ADVANCE(57);
      END_STATE();
    case 49:
      if (lookahead == 'I') ADVANCE(58);
      END_STATE();
    case 50:
      if (lookahead == 'T') ADVANCE(59);
      END_STATE();
    case 51:
      if (lookahead == 'S') ADVANCE(60);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(anon_sym_FIRES);
      END_STATE();
    case 53:
      if (lookahead == 'I') ADVANCE(61);
      END_STATE();
    case 54:
      if (lookahead == '_') ADVANCE(62);
      END_STATE();
    case 55:
      if (lookahead == 'S') ADVANCE(63);
      END_STATE();
    case 56:
      if (lookahead == 'I') ADVANCE(64);
      END_STATE();
    case 57:
      if (lookahead == 'T') ADVANCE(65);
      END_STATE();
    case 58:
      if (lookahead == 'P') ADVANCE(66);
      END_STATE();
    case 59:
      if (lookahead == 'A') ADVANCE(67);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(anon_sym_EVENTS);
      END_STATE();
    case 61:
      if (lookahead == 'O') ADVANCE(68);
      END_STATE();
    case 62:
      if (lookahead == 'S') ADVANCE(69);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(anon_sym_STATES);
      END_STATE();
    case 64:
      if (lookahead == 'T') ADVANCE(70);
      END_STATE();
    case 65:
      if (lookahead == '_') ADVANCE(71);
      END_STATE();
    case 66:
      if (lookahead == 'T') ADVANCE(72);
      END_STATE();
    case 67:
      if (lookahead == 'T') ADVANCE(73);
      END_STATE();
    case 68:
      if (lookahead == 'N') ADVANCE(74);
      END_STATE();
    case 69:
      if (lookahead == 'T') ADVANCE(75);
      END_STATE();
    case 70:
      if (lookahead == 'I') ADVANCE(76);
      END_STATE();
    case 71:
      if (lookahead == 'S') ADVANCE(77);
      END_STATE();
    case 72:
      if (lookahead == 'I') ADVANCE(78);
      END_STATE();
    case 73:
      if (lookahead == 'E') ADVANCE(79);
      END_STATE();
    case 74:
      if (lookahead == 'S') ADVANCE(80);
      END_STATE();
    case 75:
      if (lookahead == 'A') ADVANCE(81);
      END_STATE();
    case 76:
      if (lookahead == 'O') ADVANCE(82);
      END_STATE();
    case 77:
      if (lookahead == 'T') ADVANCE(83);
      END_STATE();
    case 78:
      if (lookahead == 'O') ADVANCE(84);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(anon_sym_END_STATE);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(anon_sym_REACTIONS);
      END_STATE();
    case 81:
      if (lookahead == 'T') ADVANCE(85);
      END_STATE();
    case 82:
      if (lookahead == 'N') ADVANCE(86);
      END_STATE();
    case 83:
      if (lookahead == 'A') ADVANCE(87);
      END_STATE();
    case 84:
      if (lookahead == 'N') ADVANCE(88);
      END_STATE();
    case 85:
      if (lookahead == 'E') ADVANCE(89);
      END_STATE();
    case 86:
      if (lookahead == 'S') ADVANCE(90);
      END_STATE();
    case 87:
      if (lookahead == 'T') ADVANCE(91);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(anon_sym_DESCRIPTION);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(anon_sym_START_STATE);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(anon_sym_TRANSITIONS);
      END_STATE();
    case 91:
      if (lookahead == 'E') ADVANCE(92);
      END_STATE();
    case 92:
      ACCEPT_TOKEN(anon_sym_CURRENT_STATE);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 0},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 0},
  [91] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
    [anon_sym_ns] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_NAME] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_DESCRIPTION] = ACTIONS(1),
    [anon_sym_STATES] = ACTIONS(1),
    [anon_sym_START_STATE] = ACTIONS(1),
    [anon_sym_CURRENT_STATE] = ACTIONS(1),
    [anon_sym_END_STATE] = ACTIONS(1),
    [anon_sym_EVENTS] = ACTIONS(1),
    [anon_sym_TRANSITIONS] = ACTIONS(1),
    [anon_sym_REACTIONS] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_AT] = ACTIONS(1),
    [anon_sym_FROM] = ACTIONS(1),
    [anon_sym_TO] = ACTIONS(1),
    [anon_sym_WHEN] = ACTIONS(1),
    [anon_sym_DO] = ACTIONS(1),
    [anon_sym_FIRES] = ACTIONS(1),
    [sym_string] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(86),
    [sym_namespace_decl] = STATE(3),
    [sym_fsm_definition] = STATE(56),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(5),
    [sym_comment] = ACTIONS(3),
    [anon_sym_ns] = ACTIONS(7),
    [anon_sym_NAME] = ACTIONS(9),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 2,
      ts_builtin_sym_end,
      anon_sym_COMMA,
    ACTIONS(13), 8,
      anon_sym_CURRENT_STATE,
      anon_sym_END_STATE,
      anon_sym_EVENTS,
      anon_sym_REACTIONS,
      anon_sym_TO,
      anon_sym_DO,
      anon_sym_FIRES,
      sym_identifier,
  [18] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_ns,
    ACTIONS(9), 1,
      anon_sym_NAME,
    ACTIONS(15), 1,
      ts_builtin_sym_end,
    STATE(85), 1,
      sym_fsm_definition,
    STATE(4), 2,
      sym_namespace_decl,
      aux_sym_source_file_repeat1,
  [38] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(19), 1,
      anon_sym_ns,
    ACTIONS(17), 2,
      ts_builtin_sym_end,
      anon_sym_NAME,
    STATE(4), 2,
      sym_namespace_decl,
      aux_sym_source_file_repeat1,
  [53] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(24), 1,
      anon_sym_COMMA,
    STATE(7), 1,
      aux_sym_identifier_list_repeat1,
    ACTIONS(22), 2,
      anon_sym_START_STATE,
      anon_sym_TRANSITIONS,
  [67] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(24), 1,
      anon_sym_COMMA,
    STATE(5), 1,
      aux_sym_identifier_list_repeat1,
    ACTIONS(26), 2,
      anon_sym_START_STATE,
      anon_sym_TRANSITIONS,
  [81] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(30), 1,
      anon_sym_COMMA,
    STATE(7), 1,
      aux_sym_identifier_list_repeat1,
    ACTIONS(28), 2,
      anon_sym_START_STATE,
      anon_sym_TRANSITIONS,
  [95] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(33), 1,
      anon_sym_DESCRIPTION,
    ACTIONS(35), 1,
      anon_sym_STATES,
    STATE(30), 1,
      sym_description_clause,
    STATE(34), 1,
      sym_states_clause,
  [111] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(37), 1,
      sym_identifier,
    ACTIONS(39), 1,
      anon_sym_REACTIONS,
    STATE(10), 2,
      sym_transition_def,
      aux_sym_transitions_clause_repeat1,
  [125] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(37), 1,
      sym_identifier,
    ACTIONS(41), 1,
      anon_sym_REACTIONS,
    STATE(11), 2,
      sym_transition_def,
      aux_sym_transitions_clause_repeat1,
  [139] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(43), 1,
      sym_identifier,
    ACTIONS(46), 1,
      anon_sym_REACTIONS,
    STATE(11), 2,
      sym_transition_def,
      aux_sym_transitions_clause_repeat1,
  [153] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(48), 1,
      ts_builtin_sym_end,
    ACTIONS(50), 1,
      sym_identifier,
    STATE(15), 2,
      sym_reaction_def,
      aux_sym_reactions_clause_repeat1,
  [167] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(52), 1,
      ts_builtin_sym_end,
    ACTIONS(54), 1,
      sym_identifier,
    STATE(13), 2,
      sym_reaction_def,
      aux_sym_reactions_clause_repeat1,
  [181] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(57), 1,
      ts_builtin_sym_end,
    ACTIONS(59), 1,
      sym_identifier,
    ACTIONS(61), 1,
      anon_sym_FIRES,
    STATE(43), 1,
      sym_fires_clause,
  [197] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(50), 1,
      sym_identifier,
    ACTIONS(63), 1,
      ts_builtin_sym_end,
    STATE(13), 2,
      sym_reaction_def,
      aux_sym_reactions_clause_repeat1,
  [211] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(67), 1,
      anon_sym_COMMA,
    STATE(17), 1,
      aux_sym_fires_clause_repeat1,
    ACTIONS(65), 2,
      ts_builtin_sym_end,
      sym_identifier,
  [225] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(67), 1,
      anon_sym_COMMA,
    STATE(18), 1,
      aux_sym_fires_clause_repeat1,
    ACTIONS(69), 2,
      ts_builtin_sym_end,
      sym_identifier,
  [239] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(73), 1,
      anon_sym_COMMA,
    STATE(18), 1,
      aux_sym_fires_clause_repeat1,
    ACTIONS(71), 2,
      ts_builtin_sym_end,
      sym_identifier,
  [253] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(76), 3,
      ts_builtin_sym_end,
      anon_sym_ns,
      anon_sym_NAME,
  [262] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(28), 3,
      anon_sym_START_STATE,
      anon_sym_TRANSITIONS,
      anon_sym_COMMA,
  [271] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(71), 3,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      sym_identifier,
  [280] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(78), 1,
      anon_sym_AT,
    STATE(16), 1,
      sym_reference,
  [290] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(80), 1,
      anon_sym_CURRENT_STATE,
    STATE(33), 1,
      sym_current_state_clause,
  [300] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(78), 1,
      anon_sym_AT,
    STATE(52), 1,
      sym_reference,
  [310] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(82), 1,
      anon_sym_TRANSITIONS,
    STATE(28), 1,
      sym_transitions_clause,
  [320] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(82), 1,
      anon_sym_TRANSITIONS,
    STATE(29), 1,
      sym_transitions_clause,
  [330] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(84), 1,
      sym_identifier,
    STATE(57), 1,
      sym_identifier_list,
  [340] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(86), 1,
      anon_sym_REACTIONS,
    STATE(60), 1,
      sym_reactions_clause,
  [350] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(86), 1,
      anon_sym_REACTIONS,
    STATE(61), 1,
      sym_reactions_clause,
  [360] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(35), 1,
      anon_sym_STATES,
    STATE(48), 1,
      sym_states_clause,
  [370] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(80), 1,
      anon_sym_CURRENT_STATE,
    STATE(35), 1,
      sym_current_state_clause,
  [380] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(78), 1,
      anon_sym_AT,
    STATE(78), 1,
      sym_reference,
  [390] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(88), 1,
      anon_sym_END_STATE,
    STATE(44), 1,
      sym_end_state_clause,
  [400] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(90), 1,
      anon_sym_START_STATE,
    STATE(23), 1,
      sym_start_state_clause,
  [410] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(88), 1,
      anon_sym_END_STATE,
    STATE(49), 1,
      sym_end_state_clause,
  [420] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(78), 1,
      anon_sym_AT,
    STATE(74), 1,
      sym_reference,
  [430] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(78), 1,
      anon_sym_AT,
    STATE(77), 1,
      sym_reference,
  [440] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(78), 1,
      anon_sym_AT,
    STATE(39), 1,
      sym_reference,
  [450] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(92), 2,
      anon_sym_REACTIONS,
      sym_identifier,
  [458] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(78), 1,
      anon_sym_AT,
    STATE(14), 1,
      sym_reference,
  [468] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(78), 1,
      anon_sym_AT,
    STATE(88), 1,
      sym_reference,
  [478] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(94), 1,
      anon_sym_LPAREN,
    STATE(8), 1,
      sym_qualified_name,
  [488] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(96), 2,
      ts_builtin_sym_end,
      sym_identifier,
  [496] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(98), 1,
      anon_sym_EVENTS,
    STATE(25), 1,
      sym_events_clause,
  [506] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(100), 2,
      anon_sym_DESCRIPTION,
      anon_sym_STATES,
  [514] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(78), 1,
      anon_sym_AT,
    STATE(21), 1,
      sym_reference,
  [524] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(84), 1,
      sym_identifier,
    STATE(55), 1,
      sym_identifier_list,
  [534] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(90), 1,
      anon_sym_START_STATE,
    STATE(31), 1,
      sym_start_state_clause,
  [544] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(98), 1,
      anon_sym_EVENTS,
    STATE(26), 1,
      sym_events_clause,
  [554] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(102), 1,
      anon_sym_COLON,
  [561] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(104), 1,
      anon_sym_STATES,
  [568] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(106), 1,
      anon_sym_EVENTS,
  [575] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(108), 1,
      anon_sym_ns,
  [582] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(110), 1,
      anon_sym_COLON,
  [589] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(112), 1,
      anon_sym_START_STATE,
  [596] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(15), 1,
      ts_builtin_sym_end,
  [603] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(114), 1,
      anon_sym_TRANSITIONS,
  [610] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(116), 1,
      sym_identifier,
  [617] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(118), 1,
      anon_sym_COLON,
  [624] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(120), 1,
      ts_builtin_sym_end,
  [631] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(122), 1,
      ts_builtin_sym_end,
  [638] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(124), 1,
      anon_sym_COLON,
  [645] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(126), 1,
      anon_sym_COLON,
  [652] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(128), 1,
      anon_sym_EQ,
  [659] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(130), 1,
      anon_sym_FROM,
  [666] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(132), 1,
      sym_identifier,
  [673] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(134), 1,
      anon_sym_COLON,
  [680] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(136), 1,
      sym_identifier,
  [687] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(138), 1,
      anon_sym_COLON,
  [694] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(140), 1,
      anon_sym_RPAREN,
  [701] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(142), 1,
      anon_sym_COLON,
  [708] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(144), 1,
      anon_sym_COLON,
  [715] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(146), 1,
      anon_sym_COLON,
  [722] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(148), 1,
      anon_sym_TO,
  [729] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(150), 1,
      sym_identifier,
  [736] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(152), 1,
      anon_sym_COLON,
  [743] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(154), 1,
      anon_sym_DO,
  [750] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(156), 1,
      anon_sym_CURRENT_STATE,
  [757] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(158), 1,
      anon_sym_COLON,
  [764] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(160), 1,
      anon_sym_EQ,
  [771] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(162), 1,
      anon_sym_COLON,
  [778] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(164), 1,
      anon_sym_COLON,
  [785] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(166), 1,
      sym_identifier,
  [792] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(168), 1,
      sym_string,
  [799] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(170), 1,
      ts_builtin_sym_end,
  [806] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(172), 1,
      ts_builtin_sym_end,
  [813] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(174), 1,
      anon_sym_COLON,
  [820] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(176), 1,
      anon_sym_END_STATE,
  [827] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(178), 1,
      sym_string,
  [834] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(180), 1,
      anon_sym_COLON,
  [841] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(182), 1,
      anon_sym_WHEN,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 18,
  [SMALL_STATE(4)] = 38,
  [SMALL_STATE(5)] = 53,
  [SMALL_STATE(6)] = 67,
  [SMALL_STATE(7)] = 81,
  [SMALL_STATE(8)] = 95,
  [SMALL_STATE(9)] = 111,
  [SMALL_STATE(10)] = 125,
  [SMALL_STATE(11)] = 139,
  [SMALL_STATE(12)] = 153,
  [SMALL_STATE(13)] = 167,
  [SMALL_STATE(14)] = 181,
  [SMALL_STATE(15)] = 197,
  [SMALL_STATE(16)] = 211,
  [SMALL_STATE(17)] = 225,
  [SMALL_STATE(18)] = 239,
  [SMALL_STATE(19)] = 253,
  [SMALL_STATE(20)] = 262,
  [SMALL_STATE(21)] = 271,
  [SMALL_STATE(22)] = 280,
  [SMALL_STATE(23)] = 290,
  [SMALL_STATE(24)] = 300,
  [SMALL_STATE(25)] = 310,
  [SMALL_STATE(26)] = 320,
  [SMALL_STATE(27)] = 330,
  [SMALL_STATE(28)] = 340,
  [SMALL_STATE(29)] = 350,
  [SMALL_STATE(30)] = 360,
  [SMALL_STATE(31)] = 370,
  [SMALL_STATE(32)] = 380,
  [SMALL_STATE(33)] = 390,
  [SMALL_STATE(34)] = 400,
  [SMALL_STATE(35)] = 410,
  [SMALL_STATE(36)] = 420,
  [SMALL_STATE(37)] = 430,
  [SMALL_STATE(38)] = 440,
  [SMALL_STATE(39)] = 450,
  [SMALL_STATE(40)] = 458,
  [SMALL_STATE(41)] = 468,
  [SMALL_STATE(42)] = 478,
  [SMALL_STATE(43)] = 488,
  [SMALL_STATE(44)] = 496,
  [SMALL_STATE(45)] = 506,
  [SMALL_STATE(46)] = 514,
  [SMALL_STATE(47)] = 524,
  [SMALL_STATE(48)] = 534,
  [SMALL_STATE(49)] = 544,
  [SMALL_STATE(50)] = 554,
  [SMALL_STATE(51)] = 561,
  [SMALL_STATE(52)] = 568,
  [SMALL_STATE(53)] = 575,
  [SMALL_STATE(54)] = 582,
  [SMALL_STATE(55)] = 589,
  [SMALL_STATE(56)] = 596,
  [SMALL_STATE(57)] = 603,
  [SMALL_STATE(58)] = 610,
  [SMALL_STATE(59)] = 617,
  [SMALL_STATE(60)] = 624,
  [SMALL_STATE(61)] = 631,
  [SMALL_STATE(62)] = 638,
  [SMALL_STATE(63)] = 645,
  [SMALL_STATE(64)] = 652,
  [SMALL_STATE(65)] = 659,
  [SMALL_STATE(66)] = 666,
  [SMALL_STATE(67)] = 673,
  [SMALL_STATE(68)] = 680,
  [SMALL_STATE(69)] = 687,
  [SMALL_STATE(70)] = 694,
  [SMALL_STATE(71)] = 701,
  [SMALL_STATE(72)] = 708,
  [SMALL_STATE(73)] = 715,
  [SMALL_STATE(74)] = 722,
  [SMALL_STATE(75)] = 729,
  [SMALL_STATE(76)] = 736,
  [SMALL_STATE(77)] = 743,
  [SMALL_STATE(78)] = 750,
  [SMALL_STATE(79)] = 757,
  [SMALL_STATE(80)] = 764,
  [SMALL_STATE(81)] = 771,
  [SMALL_STATE(82)] = 778,
  [SMALL_STATE(83)] = 785,
  [SMALL_STATE(84)] = 792,
  [SMALL_STATE(85)] = 799,
  [SMALL_STATE(86)] = 806,
  [SMALL_STATE(87)] = 813,
  [SMALL_STATE(88)] = 820,
  [SMALL_STATE(89)] = 827,
  [SMALL_STATE(90)] = 834,
  [SMALL_STATE(91)] = 841,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [11] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_reference, 2, 0, 0),
  [13] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_reference, 2, 0, 0),
  [15] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [17] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [19] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(58),
  [22] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_identifier_list, 2, 0, 0),
  [24] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [26] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_identifier_list, 1, 0, 0),
  [28] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_identifier_list_repeat1, 2, 0, 0),
  [30] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_identifier_list_repeat1, 2, 0, 0), SHIFT_REPEAT(68),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [37] = {.entry = {.count = 1, .reusable = false}}, SHIFT(62),
  [39] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_transitions_clause, 2, 0, 0),
  [41] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_transitions_clause, 3, 0, 0),
  [43] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_transitions_clause_repeat1, 2, 0, 0), SHIFT_REPEAT(62),
  [46] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_transitions_clause_repeat1, 2, 0, 0),
  [48] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_reactions_clause, 2, 0, 0),
  [50] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [52] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_reactions_clause_repeat1, 2, 0, 0),
  [54] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_reactions_clause_repeat1, 2, 0, 0), SHIFT_REPEAT(67),
  [57] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_reaction_def, 8, 0, 5),
  [59] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_reaction_def, 8, 0, 5),
  [61] = {.entry = {.count = 1, .reusable = false}}, SHIFT(50),
  [63] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_reactions_clause, 3, 0, 0),
  [65] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fires_clause, 3, 0, 0),
  [67] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [69] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fires_clause, 4, 0, 0),
  [71] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_fires_clause_repeat1, 2, 0, 0),
  [73] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_fires_clause_repeat1, 2, 0, 0), SHIFT_REPEAT(46),
  [76] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_namespace_decl, 4, 0, 1),
  [78] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [80] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [82] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [84] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [86] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [88] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [90] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [92] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_transition_def, 8, 0, 4),
  [94] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [96] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_reaction_def, 9, 0, 5),
  [98] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [100] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_qualified_name, 6, 0, 2),
  [102] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [104] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_description_clause, 3, 0, 0),
  [106] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_end_state_clause, 3, 0, 0),
  [108] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [110] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [112] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_states_clause, 3, 0, 0),
  [114] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_events_clause, 3, 0, 0),
  [116] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [118] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [120] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fsm_definition, 10, 0, 3),
  [122] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fsm_definition, 11, 0, 3),
  [124] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [126] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [128] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [130] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [132] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [134] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [136] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [138] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [140] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [142] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [144] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [146] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [148] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [150] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [152] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [154] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [156] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_start_state_clause, 3, 0, 0),
  [158] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [160] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [162] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [164] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [166] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [168] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [170] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 2, 0, 0),
  [172] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [174] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [176] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_current_state_clause, 3, 0, 0),
  [178] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [180] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [182] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_fsm(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
